apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
  labels:
    svc: lb-nginx-svc
spec:
  type: NodePort
  ports:
    - port: 8015
      targetPort: 80
      nodePort: 31095
  selector:
    app: nginx-lw-deployment-label

