apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql-0
spec:
  capacity:
    storage: 1Gi
  accessModes: 
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  #storageClassName: "redis-cluster"
  nfs:
    path: /data/fileshare/mysql0
    server: 10.0.2.8
