apiVersion: v1
kind: Service
metadata:
  name: nginx-serv-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-lw-deployment-label
  ports:
   - protocol: TCP
     nodePort: 30000
     port: 8080
     targetPort: 80
