apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: normal-service-provider-svc-fault-delay
spec:
  hosts:
  - normal-service-provider-svc
  http:
  - fault:
      delay:
        fixedDelay: 4s
        percent: 70
    route:
    - destination:
        host: normal-service-provider-svc
        subset: v1
      
